name: tests

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
